### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Paptoos** [Ferdosi-lang/Ferdosi-Python-Interpreter#14]
سلام
من یک لوگوی بسیار ساده طراحی کردم
اگر خوشتان آمد بفرمایید با چه رنگی درست کنم
و اگر خوشتان نیامد می توانید این issue را ببندید
لوگو با رنگ آبی ، سفید و سیاه :
![لوگو](https://user-images.githubusercontent.com/72940447/97801753-28118700-1c54-11eb-87ee-717abc8056c0.jpg)

**Comment by AshkanLaei** [comment]
سلام همین رنگ قشنگه ولی بهتر نیست جای سلام دنیا یه عبارت پرربط تر باشه؟

**Comment by Paptoos** [comment]
خیلی هم عالی ، به نظر شما چه عبارتی

**Comment by Paptoos** [comment]
مثلا " فارسی برنامه بنویسید " خوبه ؟

**Comment by AshkanLaei** [comment]
<div dir=rtl>برای مثال «فارسی ترین زبان برنامه نویسی»! یا همون که خودت گفتی «فارسی برنامه بنویس»</div>

**Comment by Paptoos** [comment]
فارسی ترین زبان برنامه نویسی قشنگ تره
الان طراحی و ارسال می کنم

**Comment by Paptoos** [comment]
![Uploading Untitled-1.jpg…]()

**Comment by Paptoos** [comment]
فایل آپلود نمی شود

**Comment by Paptoos** [comment]
لینکش را ارسال می کنم

**Comment by Paptoos** [comment]
https://mega.nz/file/FlUVHYQA#rKw3NzAHvPhAp_aMCLfSavjB_jbFExP8pjwdGaw2BRQ

**Comment by AshkanLaei** [comment]
<div dir=rtl>قشنگه. میزارمش توی readme</div>

**Comment by Paptoos** [comment]
ممنون
