### ISSUE TITLE
کلاس‌های تعریف شده در فایل مفسر

### ISSUE THREAD

**Issue by farooqkz** [Ferdosi-lang/Ferdosi-Python-Interpreter#25]
<div dir="rtl">

کلاس PPLExecute که در فایل مفسر تعریف شدند خروجی رو چاپ میکنند
بنده نیاز دارم که خروجی‌ها رو از کلاس بگیرم. حتی خطاهای برنامه کاربر رو.

اگر میخواید خودم یک عدد پول رکوئست بدم

**Comment by Paptoos** [comment]
منظورتون رو متوجه نمی شم !

**Comment by Paptoos** [comment]
پول ریگوئست بدید ، تا منظورتان را متوجه شوم

**Comment by farooqkz** [comment]
> پول ریگوئست بدید ، تا منظورتان را متوجه شوم

ببینید. کلاس مربوطه کد نوشته شده به زبان فردوسی رو اجرا میکنه و نتایج رو تک به تک با تابع print() میفرسته به خروجی، درسته؟
خب من میخوام جای دیگه نتایج رو نشون بدم پس باید یک جوری خروجی رو از کلاس بگیرم و هر طور که میخوام نمایششون بدم.

**Comment by Paptoos** [comment]
خیلی هم عالی
خب بپول ریگوئستید و این رو درست کنید

**Comment by farooqkz** [comment]
چشم کمی زمان به من بدید
