### ISSUE TITLE
استفاده از فاصله بجای تب؟

### ISSUE THREAD

**Issue by farooqkz** [Ferdosi-lang/Ferdosi-Python-Interpreter#29]
<div dir="rtl">

من متوجه شدم که شما در فایل مفسر به جای اسپیس از تب استفاده می‌کنید. به این دو دلیل پیشنهاد میکنم به اسپیس مهاجرت کنید:
 - تب هر جا یک اندازه‌ای داره(مثلا با گیت‌هاب کدتون رو ببینید که چه بلایی سرش در اومده!) و این در حالیه که سطح دندانه گذاری استاندارد برای پایتون ۴ هست
 - PEP8 هم استفاده از تب رو پیشنهاد نمی‌کنه

**Comment by farooqkz** [comment]
اگر موافق این مهاجرت هستید تا من یک پول رکوئست بفرستم

**Comment by AshkanLaei** [comment]
باشه بفرست. من اکثر جا ها از تب استفاده میکنم چون قابلیت شخصی سازی داره هم میشه اندازش رو تغییر داد هم استفادش مشخصه (فقط برای تورفتگی استفاده میشه)

**Comment by Paptoos** [comment]
سلام
من موافقم ، فقط مشکل این هست که هر کی با ادیتور خودش کار می کنه و هر ادیتوری یک جوری کد رو فرمت می کنه

**Comment by Paptoos** [comment]
تب دو استاندارد 8 و 4 اسپیس رو داره ، توی گیت هاب 8 اسپیس ، توی وی اس کد ، 4 اسپیس ، سابلایم رو نمی دونم ولی فکر کنم 4 باشه

**Comment by AshkanLaei** [comment]
خب خوبیش همینه دیگه هر کسی متناسب با سلیقش کد رو میبینه! ولی آره خوبه با اسپیس هم

**Comment by Paptoos** [comment]
خب مواقع پول ریگوئست باید حواسمون به این موضوع باشه

**Comment by farooqkz** [comment]
> خب خوبیش همینه دیگه هر کسی متناسب با سلیقش کد رو میبینه! ولی آره خوبه با اسپیس هم

بحث سلیقه نیست. اگر از تعداد نا معقولی اسپیس استفاده کنیم برای دندانه گزاری توی هر زبانی خوندن کد سخت میشه.

ادیتور هایی که برای برنامه نویسی ساخته شدن رو هم میشه کانفیگ کرد

مثلا من ویم رو اینطور کانفیگ کردم که عرض هر تب ۴ باشه و زمانی که کلید تب رو میزنم ۴ اسپیس بزاره به جای تب و برای حذف کردن چهار اسپیس هم یا از d4h استفاده میکنم یا dw

**Comment by Paptoos** [comment]
من به شخصه از ویژوال استودیو کد استفاده می کنم و خوبی این ادیتور:
Alt+Shift+F
کد را به صورت درست و مرتب و استاندارد می کند

**Comment by farooqkz** [comment]
نهههههه ادیتور من بهتره :joy: 

همینجوری بیش بریم دعوا میشه

**Comment by Paptoos** [comment]
آره ولش کن ، پول ری گوئست چی شد ؟

**Comment by farooqkz** [comment]
دارم rebase میکنم

عجله نداشته باشید

**Comment by Paptoos** [comment]
الان که پول ریگوئست دادی ، می تونی ایشو رو ببندی ؟

**Comment by farooqkz** [comment]
بنظرم زمانی باید ایشو بسته بشه که مشکل حل شده باشه یا تغییر اعمال شده باشه یا ویژگی اضافه شده باشه اما پروژه‌ی من که نیست پس  اگر فکر میکنید باید بسته بشه خودتون ببندینش

**Comment by Paptoos** [comment]
حق با شماست ، من هم رایت اکسس ندارم و فقط آقا اشکان مدیر پروژه است

**Comment by Paptoos** [comment]
ولی باید صبر کرد تا مرج شه 👍
